.TH Chess256 6 "January  7 2018"
.SH NAME
chess256 \- chess application for playing, editing and analysing games.

.SH SYNOPSIS
.B chess256

.SH DESCRIPTION

.SH About the program
\fBChess256\fR is a chess program for playing, editing and analysing chess games. This project was supposed to be a very powerful chess application, but many features are missing by now. Though, many basic things have been already implemented.
.PP
The project is in \fBALPHA\fR state.

.SH Features
* Support for standard chess formats (PGN for chess notation, FEN for positions and UCI chess protocol).
.PP
* Powerful PGN editor (support for comments, NAGs, variations...).
.PP
* Playing games between players, between engines and player vs engine.
.PP
* Also there is analysis mode, where you can add variations, comments, etc.
.PP
* Advanced time control options (you can define options like this: \fI2 hours per 40 moves, then 1 hour per following 20 moves and then 1 hour for the rest of the game\fR.

* Written on \fBFree Pascal\fR using \fBLazarus IDE\fR

.SH Missing things

* Game analysis.

* Charts showing position cost change in different moments of time.

* Notation nodes showing position cost and time stamp.

* Advanced notation features, such as diagrams.

* Games database.

* Support for a wider range of chess engines (WinBoard/XBoard, ...)

* Notation printing and exporting (to RTF, PDF, ...)

* Customization, custom icon sets, board pieces, etc.

.SH OPTIONS
At this moment of time, all the options are ignored.

.SH AUTHORS
Alexander Kernozhitsky <sh200105@mail.ru>
